name: simple_box
description: A simple state management solution that uses streams.
version: 1.0.8
repository: https://github.com/Alizendah93/simple-box.git
homepage: https://pub.dev/packages/simple_box

environment:
  sdk: '>=3.10.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints:
  test:
  flutter_test:
    sdk: flutter
