name: simple_box
description: A simple state management solution that uses streams.
version: 1.0.0
homepage: https://github.com/Alizendah93/simple-box.git

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
